version: '3.8'

services:
  db:
    image:  postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5443:5443"

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      FLASK_ENV: development
      DATABASE_URL: postgresql+psycopg2://postgres:123@db:5443/postgres
    depends_on:
      - db

volumes:
  postgres_data:
