version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: flask run --host=0.0.0.0
    volumes:
      - ./flask/app/application:/app/app
    ports:
      - "8000:8000"
    environment:
      FLASK_ENV: development
      DATABASE_URL: postgresql+psycopg2://myuser:mypassword@db:5432/mydatabase
    depends_on:
      - db

volumes:
  postgres_data:
